# Generated by Django 3.1.14 on 2025-11-14 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('link_video', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('isi', models.TextField()),
                ('potensi', models.TextField(blank=True, null=True)),
                ('inovator', models.CharField(blank=True, max_length=200, null=True)),
                ('institusi', models.CharField(blank=True, max_length=100, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='berita/')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=200)),
                ('institusi', models.CharField(blank=True, max_length=200)),
                ('no_hp', models.CharField(blank=True, max_length=15, null=True, verbose_name='No.HP')),
                ('foto_profil', models.ImageField(default='default.jpeg', upload_to='foto_profil/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_komentar', models.TextField()),
                ('tanggal_komentar', models.DateTimeField(auto_now_add=True)),
                ('inovasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='data_kampus.berita')),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tanggal_komentar'],
            },
        ),
        migrations.AddField(
            model_name='berita',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_kampus.kategori'),
        ),
        migrations.AddField(
            model_name='berita',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_inovasi', to=settings.AUTH_USER_MODEL),
        ),
    ]
